# Generated by Django 5.1.2 on 2024-10-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Descriptive Answer',
                'verbose_name_plural': 'Descriptive Answers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MatrixAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Matrix Answer',
                'verbose_name_plural': 'Matrix Answers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Multiple Choice Answer',
                'verbose_name_plural': 'Multiple Choice Answers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NumericAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Numeric Answer',
                'verbose_name_plural': 'Numeric Answers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['survey'],
            },
        ),
    ]
